### ISSUE TITLE
Error building extension '_slangtorch_texture_baker_44136fa355b3678a'

### ISSUE THREAD

**Issue by jx3333** [YanWenKun/ComfyUI-Windows-Portable#29]
从 https://github.com/YanWenKun/ComfyUI-Windows-Portable/releases  里下载了10月29号版本的，运行stable fast3D的时候报错：
```
!!! Exception during processing !!! Error building extension '_slangtorch_texture_baker_44136fa355b3678a': [1/2] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin\nvcc --generate-dependencies-with-compile --dependency-output texture_baker_cuda.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=_slangtorch_texture_baker_44136fa355b3678a -DTORCH_API_INCLUDE_EXTENSION_H -IE:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\StableFast3D\sf3d -IE:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch\include -IE:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch\include\torch\csrc\api\include -IE:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch\include\TH -IE:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include" -IE:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\python_embeded\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 -std=c++17 --std=c++17 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -DSLANG_CUDA_ENABLE_HALF=1 -c E:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\StableFast3D\sf3d\.slangtorch_cache\texture_baker\44136fa355b3678a\texture_baker_cuda.cu -o texture_baker_cuda.cuda.o 

FAILED: texture_baker_cuda.cuda.o 

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin\nvcc --generate-dependencies-with-compile --dependency-output texture_baker_cuda.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=_slangtorch_texture_baker_44136fa355b3678a -DTORCH_API_INCLUDE_EXTENSION_H -IE:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\StableFast3D\sf3d -IE:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch\include -IE:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch\include\torch\csrc\api\include -IE:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch\include\TH -IE:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include" -IE:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\python_embeded\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 -std=c++17 --std=c++17 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -DSLANG_CUDA_ENABLE_HALF=1 -c E:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\StableFast3D\sf3d\.slangtorch_cache\texture_baker\44136fa355b3678a\texture_baker_cuda.cu -o texture_baker_cuda.cuda.o 

ninja: build stopped: subcommand failed.


[2024-10-30 11:24:53.450] Traceback (most recent call last):
  File "E:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 2104, in _run_ninja_build
    subprocess.run(
  File "subprocess.py", line 571, in run
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 1983, in load_SF3D
    sf3d_model = SF3D.from_pretrained(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "E:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\StableFast3D\sf3d\system.py", line 78, in from_pretrained
    model = cls(cfg)
            ^^^^^^^^
  File "E:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\StableFast3D\sf3d\models\utils.py", line 29, in __init__
    self.configure(*args, **kwargs)
  File "E:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\StableFast3D\sf3d\system.py", line 128, in configure
    self.baker = TextureBaker()
                 ^^^^^^^^^^^^^^
  File "E:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\StableFast3D\sf3d\texture_baker.py", line 13, in __init__
    self.baker = slangtorch.loadModule(
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\slangtorch\slangtorch.py", line 652, in loadModule
    rawModule = _loadModule(fileName, moduleName, buildDir, options, sourceDir=outputFolder, verbose=verbose, includePaths=includePaths, dryRun=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\slangtorch\slangtorch.py", line 571, in _loadModule
    slangLib, metadata = compileAndLoadModule(
                         ^^^^^^^^^^^^^^^^^^^^^
  File "E:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\slangtorch\slangtorch.py", line 460, in compileAndLoadModule
    slangLib = _compileAndLoadModule(metadata, sources, moduleName, buildDir, slangSourceDir, verbose)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\slangtorch\slangtorch.py", line 501, in _compileAndLoadModule
    return jit_compile(
           ^^^^^^^^^^^^
  File "E:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\slangtorch\util\compile.py", line 71, in jit_compile
    _write_ninja_file_and_build_library(
  File "E:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1833, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "E:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 2120, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension '_slangtorch_texture_baker_44136fa355b3678a': [1/2] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin\nvcc --generate-dependencies-with-compile --dependency-output texture_baker_cuda.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=_slangtorch_texture_baker_44136fa355b3678a -DTORCH_API_INCLUDE_EXTENSION_H -IE:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\StableFast3D\sf3d -IE:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch\include -IE:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch\include\torch\csrc\api\include -IE:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch\include\TH -IE:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include" -IE:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\python_embeded\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 -std=c++17 --std=c++17 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -DSLANG_CUDA_ENABLE_HALF=1 -c E:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\StableFast3D\sf3d\.slangtorch_cache\texture_baker\44136fa355b3678a\texture_baker_cuda.cu -o texture_baker_cuda.cuda.o 

FAILED: texture_baker_cuda.cuda.o 

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin\nvcc --generate-dependencies-with-compile --dependency-output texture_baker_cuda.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=_slangtorch_texture_baker_44136fa355b3678a -DTORCH_API_INCLUDE_EXTENSION_H -IE:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\StableFast3D\sf3d -IE:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch\include -IE:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch\include\torch\csrc\api\include -IE:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch\include\TH -IE:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include" -IE:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\python_embeded\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 -std=c++17 --std=c++17 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -DSLANG_CUDA_ENABLE_HALF=1 -c E:\3D\ComfyUI_Windows_portable_cu124\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\StableFast3D\sf3d\.slangtorch_cache\texture_baker\44136fa355b3678a\texture_baker_cuda.cu -o texture_baker_cuda.cuda.o 

ninja: build stopped: subcommand failed.
```

**Comment by YanWenKun** [comment]
卸载 CUDA Toolkit 12.1，安装 [CUDA Toolkit 12.4.1](https://developer.nvidia.com/cuda-12-4-1-download-archive?target_os=Windows&target_arch=x86_64&target_version=11&target_type=exe_network)，并且只需勾选安装 [Libraries 与 Compilers](https://github.com/YanWenKun/ComfyUI-Windows-Portable/blob/main/docs/cuda-toolkit-install-selection.webp)。

**Comment by YanWenKun** [comment]
基本可以确定是细碎的兼容性问题了，建议换成基于 PyTorch 2.4 的 [2024/10/18](https://github.com/YanWenKun/ComfyUI-Windows-Portable/releases/tag/v5.1) 版本看看。

以下是我的测试情况：

使用基于 PyTorch 2.5.0 的 [2024/10/29](https://github.com/YanWenKun/ComfyUI-Windows-Portable/releases/tag/v6.1) 版本：补充 ankerl\unordered_dense.h 文件后可以正常运行 SF3D 工作流

基于 PyTorch 2.5.1 的测试版（未发布），运行 3D-Pack 提供的 SF3D 工作流：`slangtorch` 报错

基于 PyTorch 2.5.1 的测试版（未发布），运行 SF3D 官方的演示工作流：编译依赖项后成功

排除影响：与 `TORCH_CUDA_ARCH_LIST` 无关

**Comment by YanWenKun** [comment]
在 Linux 上进行了更多测试：

PyTorch 2.3.0 完全正常
PyTorch 2.5.0 添加 `ankerl/unordered_dense.h` 后正常
PyTorch 2.5.1 报错：

```
In file included from /root/ComfyUI/custom_nodes/ComfyUI-3D-Pack/Gen_3D_Modules/StableFast3D/sf3d/.slangtorch_cache/texture_baker/b9c103f6b206b8e5/texture_baker.cpp:4:
/usr/local/lib64/python3.12/site-packages/torch/include/ATen/cuda/CUDAUtils.h: In function ‘bool at::cuda::check_device(c10::ArrayRef<at::Tensor>)’:
/usr/local/lib64/python3.12/site-packages/torch/include/ATen/cuda/CUDAUtils.h:14:26: error: cannot increment a pointer to incomplete type ‘const at::Tensor’
   14 |   for (const Tensor& t : ts) {
      |                          ^~
/usr/local/lib64/python3.12/site-packages/torch/include/ATen/cuda/CUDAUtils.h:15:9: error: invalid use of incomplete type ‘const class at::Tensor’
   15 |     if (t.device() != curDevice) return false;
      |         ^
In file included from /usr/local/lib64/python3.12/site-packages/torch/include/c10/core/GeneratorImpl.h:8,
                 from /usr/local/lib64/python3.12/site-packages/torch/include/ATen/core/Generator.h:18,
                 from /usr/local/lib64/python3.12/site-packages/torch/include/ATen/CPUGeneratorImpl.h:3,
                 from /usr/local/lib64/python3.12/site-packages/torch/include/ATen/Context.h:4,
                 from /usr/local/lib64/python3.12/site-packages/torch/include/ATen/cuda/CUDAContext.h:6,
                 from /root/ComfyUI/custom_nodes/ComfyUI-3D-Pack/Gen_3D_Modules/StableFast3D/sf3d/.slangtorch_cache/texture_baker/b9c103f6b206b8e5/texture_baker.cpp:3:
/usr/local/lib64/python3.12/site-packages/torch/include/c10/core/TensorImpl.h:61:7: note: forward declaration of ‘class at::Tensor’
   61 | class Tensor;
      |       ^~~~~~
ninja: build stopped: subcommand failed.
```

基本能判断是 PyTorch 2.5.1 所致，但本人能力有限，从更新 diff 中看不出什么缘由来，就此止步。

综合来看，3D-Pack 的版本兼容性其实是 PT2.3 最佳，至少目前如此。我考虑在文档中说明。

**Comment by jx3333** [comment]
> 在 Linux 上进行了更多测试：
> 
> PyTorch 2.3.0 完全正常 PyTorch 2.5.0 添加 `ankerl/unordered_dense.h` 后正常 PyTorch 2.5.1 报错：
> 
> ```
> In file included from /root/ComfyUI/custom_nodes/ComfyUI-3D-Pack/Gen_3D_Modules/StableFast3D/sf3d/.slangtorch_cache/texture_baker/b9c103f6b206b8e5/texture_baker.cpp:4:
> /usr/local/lib64/python3.12/site-packages/torch/include/ATen/cuda/CUDAUtils.h: In function ‘bool at::cuda::check_device(c10::ArrayRef<at::Tensor>)’:
> /usr/local/lib64/python3.12/site-packages/torch/include/ATen/cuda/CUDAUtils.h:14:26: error: cannot increment a pointer to incomplete type ‘const at::Tensor’
>    14 |   for (const Tensor& t : ts) {
>       |                          ^~
> /usr/local/lib64/python3.12/site-packages/torch/include/ATen/cuda/CUDAUtils.h:15:9: error: invalid use of incomplete type ‘const class at::Tensor’
>    15 |     if (t.device() != curDevice) return false;
>       |         ^
> In file included from /usr/local/lib64/python3.12/site-packages/torch/include/c10/core/GeneratorImpl.h:8,
>                  from /usr/local/lib64/python3.12/site-packages/torch/include/ATen/core/Generator.h:18,
>                  from /usr/local/lib64/python3.12/site-packages/torch/include/ATen/CPUGeneratorImpl.h:3,
>                  from /usr/local/lib64/python3.12/site-packages/torch/include/ATen/Context.h:4,
>                  from /usr/local/lib64/python3.12/site-packages/torch/include/ATen/cuda/CUDAContext.h:6,
>                  from /root/ComfyUI/custom_nodes/ComfyUI-3D-Pack/Gen_3D_Modules/StableFast3D/sf3d/.slangtorch_cache/texture_baker/b9c103f6b206b8e5/texture_baker.cpp:3:
> /usr/local/lib64/python3.12/site-packages/torch/include/c10/core/TensorImpl.h:61:7: note: forward declaration of ‘class at::Tensor’
>    61 | class Tensor;
>       |       ^~~~~~
> ninja: build stopped: subcommand failed.
> ```
> 
> 基本能判断是 PyTorch 2.5.1 所致，但本人能力有限，从更新 diff 中看不出什么缘由来，就此止步。
> 
> 综合来看，3D-Pack 的版本兼容性其实是 PT2.3 最佳，至少目前如此。我考虑在文档中说明。


非常感谢这么详细的回答，试过了 [9月10号](https://github.com/YanWenKun/ComfyUI-Windows-Portable/releases/tag/v4.2)的这个版本，还是不行，，然后把安装了cuda toolkit12.4，还是不行，哎，这些兼容性搞死人，我再继续研究研究

**Comment by YanWenKun** [comment]
@jx3333 [StableFast3D](https://github.com/Stability-AI/stable-fast-3d) 官方其实对 win/mac 都是实验性支持，因为 Torch C++ 扩展需要运行时编译，而 Linux 下用 GCC 要清晰便利很多。
所以我建议试试 Docker，Windows 下用 [Docker Desktop](https://www.docker.com/products/docker-desktop/) 即可，容器运行的成功率很高，就是配置运行会麻烦一些，镜像可以用我做的 [Comfy3D 专门镜像](https://github.com/YanWenKun/ComfyUI-Docker/blob/main/comfy3d-pt23/README.zh.adoc)，目前还没收到过无法运行的反馈。

除此之外，我在尝试给 StableFast3D 单独打一个包，用其官方提供的 comfy 插件与工作流，但不确定能不能成功做出来。

我也确实喜欢 TripoSR - StableFast3D 的理念，是个很有趣的路线。

**Comment by YanWenKun** [comment]
@jx3333 
单独打包成功了，试试看吧：
https://github.com/YanWenKun/StableFast3D-WinPortable/blob/main/README.zh.adoc
