### ISSUE TITLE
CharacterGen Update of Comfy3d-Pack brokes environment 

### ISSUE THREAD

**Issue by zafirexd** [YanWenKun/ComfyUI-Windows-Portable#5]
Fail on installation of update 3d-pack update from manager, i see a lot of "requires...but you have...which is incompatible" blah blah blah and 100 error lines, so needs for a new environment for this update, please update, 3d pack is really a pain but is so useful.

**Comment by YanWenKun** [comment]
Yep! I was aware of the 3D-Pack's `dev` branch and ready for its major update. Now it seems good to go. Check out the new release!

**Comment by zafirexd** [comment]
Working, thanks!.

**Comment by CristianMaza** [comment]
Hey, I was trying to install the Comfy3d-Pack on my existing ComfyUI installation but I was unsuccessful. 
I just found this repo and I went to download and install the latest release (11 hours ago https://github.com/YanWenKun/ComfyUI-Windows-Portable/releases/tag/v3.11) hoping to get ComfyUI with Comfy3D-Pack installed but I get the same errors:

...
 0.6 seconds: D:\ComfyUI\NewComfy\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\ComfyUI\custom_nodes\comfy_mtb
   0.7 seconds: D:\ComfyUI\NewComfy\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
   0.9 seconds: D:\ComfyUI\NewComfy\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.9 seconds (IMPORT FAILED): D:\ComfyUI\NewComfy\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack
   1.2 seconds: D:\ComfyUI\NewComfy\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
   2.7 seconds: D:\ComfyUI\NewComfy\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools

WARNING: some comfy_extras/ nodes did not import correctly. This may be because they are missing some dependencies.

IMPORT FAILED: nodes_audio.py

This issue might be caused by new missing dependencies added the last time you updated ComfyUI.
Please run the update script: update/update_comfyui.bat

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: D:\ComfyUI\NewComfy\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]

Is there a way to fix it? I simply downloaded and installed the latest version, then I started run_nvidia_gpu.bat (I haven't even moved my checkpoints to the new installation folder)

**Comment by YanWenKun** [comment]
@CristianMaza I need detailed error message about 3D-Pack. It should be somewhere before '(IMPORT FAILED)', and likely start with "Traceback".

**Comment by CristianMaza** [comment]
Thanks for the reply, there's the Traceback:

Total VRAM 24576 MB, total RAM 65349 MB
pytorch version: 2.3.0+cu118
xformers version: 0.0.26.post1+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Using xformers cross attention
Traceback (most recent call last):
  File "D:\ComfyUI\NewComfy\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\ComfyUI\nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\NewComfy\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\ComfyUI\comfy_extras\nodes_audio.py", line 1, in <module>
    import torchaudio
  File "D:\ComfyUI\NewComfy\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torchaudio\__init__.py", line 2, in <module>
    from . import _extension  # noqa  # usort: skip
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\NewComfy\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torchaudio\_extension\__init__.py", line 38, in <module>
    _load_lib("libtorchaudio")
  File "D:\ComfyUI\NewComfy\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torchaudio\_extension\utils.py", line 60, in _load_lib
    torch.ops.load_library(path)
  File "D:\ComfyUI\NewComfy\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch\_ops.py", line 1032, in load_library
    ctypes.CDLL(path)
  File "ctypes\__init__.py", line 376, in __init__
FileNotFoundError: Could not find module 'D:\ComfyUI\NewComfy\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torchaudio\lib\libtorchaudio.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

Cannot import D:\ComfyUI\NewComfy\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\ComfyUI\comfy_extras\nodes_audio.py module for custom nodes: Could not find module 'D:\ComfyUI\NewComfy\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torchaudio\lib\libtorchaudio.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
Traceback (most recent call last):
  File "D:\ComfyUI\NewComfy\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\ComfyUI\nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\NewComfy\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 47, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\NewComfy\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 48, in <module>
    from FlexiCubes.flexicubes_trainer import FlexiCubesTrainer
  File "D:\ComfyUI\NewComfy\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\MVs_Algorithms\FlexiCubes\flexicubes_trainer.py", line 13, in <module>
    from .loss import sdf_reg_loss
  File "D:\ComfyUI\NewComfy\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\MVs_Algorithms\FlexiCubes\loss.py", line 9, in <module>
    import torch_scatter
  File "D:\ComfyUI\NewComfy\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch_scatter\__init__.py", line 16, in <module>
    torch.ops.load_library(spec.origin)
  File "D:\ComfyUI\NewComfy\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch\_ops.py", line 1032, in load_library
    ctypes.CDLL(path)
  File "ctypes\__init__.py", line 376, in __init__
FileNotFoundError: Could not find module 'D:\ComfyUI\NewComfy\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch_scatter\_scatter_cuda.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

Cannot import D:\ComfyUI\NewComfy\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack module for custom nodes: Could not find module 'D:\ComfyUI\NewComfy\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch_scatter\_scatter_cuda.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

I only tried "Try fix" from the Manager but it didn't work

**Comment by YanWenKun** [comment]
> pytorch version: 2.3.0+cu118
> xformers version: 0.0.26.post1+cu118
> 
>  FileNotFoundError: Could not find module 'D:\ComfyUI\NewComfy\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torchaudio\lib\libtorchaudio.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
>
>  FileNotFoundError: Could not find module 'D:\ComfyUI\NewComfy\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch_scatter_scatter_cuda.pyd' (or one of its dependencies). Try using the full path with constructor syntax.


@CristianMaza 
The error message told that Torchaudio & PyTorch Scatter can't be found. But both of them are in the AIO package.

And the [latest release](https://github.com/YanWenKun/ComfyUI-Windows-Portable/releases/tag/v3.11) is based on:
PyTorch 2.3.1
xFormers 0.0.27
CUDA 12.1
And shouldn't be the versions showed in log.

I guess you did some installation/update that messed up the Python libraries.

I would suggest:
1. Clean things up
2. Don't change anything, make a fresh start
3. Add more custom nodes you need, one by one, until you find the broken one

**Comment by zafirexd** [comment]
@CristianMaza I got the same error, i just migrate my checkpoints to a new comfy instance, the [last release](https://github.com/YanWenKun/ComfyUI-Windows-Portable/releases/tag/v3.11) works well...but 3d-pack will always be a pain, and i have a dedicate instance for 3d pack because ALWAYS has been a pain, and an instance for images and video, i dont recommend to update until everything is stable, min 2 weeks or a month, and use multiple instances if you dont know if the new custom nodes would break something, see requirements, issues and instructions before doing anything.

**Comment by CristianMaza** [comment]
> > pytorch version: 2.3.0+cu118
> > xformers version: 0.0.26.post1+cu118
> > FileNotFoundError: Could not find module 'D:\ComfyUI\NewComfy\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torchaudio\lib\libtorchaudio.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
> > FileNotFoundError: Could not find module 'D:\ComfyUI\NewComfy\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch_scatter_scatter_cuda.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
> 
> @CristianMaza The error message told that Torchaudio & PyTorch Scatter can't be found. But both of them are in the AIO package.
> 
> And the [latest release](https://github.com/YanWenKun/ComfyUI-Windows-Portable/releases/tag/v3.11) is based on: PyTorch 2.3.1 xFormers 0.0.27 CUDA 12.1 And shouldn't be the versions showed in log.
> 
> I guess you did some installation/update that messed up the Python libraries.
> 
> I would suggest:
> 
> 1. Clean things up
> 2. Don't change anything, make a fresh start
> 3. Add more custom nodes you need, one by one, until you find the broken one

Right, it was my mistake, I tried using the Fix option in Comfy Manager and then I copied that log. 

Here I made a fresh start, I simply downloaded the .zips, extracted them and ran the .bat
This is the Traceback:

Total VRAM 24576 MB, total RAM 65349 MB
pytorch version: 2.3.1+cu121
xformers version: 0.0.27
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Using xformers cross attention
Warn!: xFormers is available (Attention)
Warn!: D:\ComfyUI-Portable\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py:1967: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(

Warn!: Traceback (most recent call last):
  File "D:\ComfyUI-Portable\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\ComfyUI\nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI-Portable\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 47, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI-Portable\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 78, in <module>
    from Unique3D.scripts.project_mesh import multiview_color_projection, get_cameras_list
  File "D:\ComfyUI-Portable\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\Unique3D\scripts\project_mesh.py", line 98, in <module>
    pix2faces_renderer = Pix2FacesRenderer()
                         ^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-Portable\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\Unique3D\scripts\project_mesh.py", line 70, in __init__
    self._glctx = dr.RasterizeGLContext(output_db=False, device=device)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-Portable\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\nvdiffrast\torch\ops.py", line 221, in __init__
    self.cpp_wrapper = _get_plugin(gl=True).RasterizeGLStateWrapper(output_db, mode == 'automatic', cuda_device_idx)
                       ^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-Portable\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\nvdiffrast\torch\ops.py", line 118, in _get_plugin
    torch.utils.cpp_extension.load(name=plugin_name, sources=source_paths, extra_cflags=opts, extra_cuda_cflags=opts+['-lineinfo'], extra_ldflags=ldflags, with_cuda=True, verbose=False)
  File "D:\ComfyUI-Portable\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1309, in load
    return _jit_compile(
           ^^^^^^^^^^^^^
  File "D:\ComfyUI-Portable\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1745, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-Portable\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 2143, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: DLL load failed while importing nvdiffrast_plugin_gl: The specified module could not be found.

Warn!: Cannot import D:\ComfyUI-Portable\ComfyUI_Windows_portable_cu121\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack module for custom nodes: DLL load failed while importing nvdiffrast_plugin_gl: The specified module could not be found.

**Comment by CristianMaza** [comment]
As [#6 (comment)](https://github.com/YanWenKun/ComfyUI-Windows-Portable/issues/6#issuecomment-2240818968) pointed out, I needed to install CUDA Toolkit 12.1 (I previously had 11.8 on my PC). After installing the newer version, this ComfyUI installation now works perfectly!
